version: "3"

services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - default
    volumes:
      - "guappmysql:/var/lib/mysql"
